[build]
  command = "npm run build"
  publish = "dist"

# Handle JSON files properly
[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"

# Handle image files
[[headers]]
  for = "*.webp"
  [headers.values]
    Content-Type = "image/webp"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=31536000"

# Force JSON files to be served as static files
[[redirects]]
  from = "/data.json"
  to = "/data.json"
  status = 200
  force = true

[[redirects]]
  from = "/data-gallery.json"
  to = "/data-gallery.json"
  status = 200
  force = true

[[redirects]]
  from = "/data-collections.json"
  to = "/data-collections.json"
  status = 200
  force = true

[[redirects]]
  from = "/data-story.json"
  to = "/data-story.json"
  status = 200
  force = true

# Fallback for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
