headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\roytu\\Desktop\\artwithheartandgifts\\backend\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\roytu\\Desktop\\artwithheartandgifts\\backend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "*.json"

[headers.values]
Content-Type = "application/json"
Cache-Control = "public, max-age=3600"

[[headers]]
for = "*.webp"

[headers.values]
Content-Type = "image/webp"
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.jpg"

[headers.values]
Content-Type = "image/jpeg"
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.png"

[headers.values]
Content-Type = "image/png"
Cache-Control = "public, max-age=31536000"

[[redirects]]
from = "/data.json"
to = "/data.json"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/data-gallery.json"
to = "/data-gallery.json"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/data-collections.json"
to = "/data-collections.json"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/data-story.json"
to = "/data-story.json"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]